function plot_fields(subplot_index, X, Y, V, posMinBound, posMaxBound, Vmax)
    subplot(3, 1, subplot_index);
    hold on;
    
    surf(X, Y, V);
    axis equal;
    axis([
        posMinBound(1), ...
        posMaxBound(1), ...
        posMinBound(2), ...
        posMaxBound(2), ...
        0, ...
        Vmax ...
    ]);
end