brisk:
  # radiusList defines the radius of each subsequent circle (in pixels). All
  # numbers must be positive. Cannot be empty.
  #
  # Default: radiusList = {0.0, 2.47, 4.17, 6.29, 9.18}
  #
  radiusList: {0.0, 2.47, 4.17, 6.29, 9.18}

  # numberList defines the number of points in each circle. Must be the same
  # size as radiusList. All numbers must be positive. Cannot be empty.
  #
  # Default: numberList = {1, 10, 14, 15, 20}
  #
  numberList: {1, 10, 14, 15, 20}

  # dMax and dMin are threshold distances to classify a pair of points as a
  # long pair or a short pair. Short pairs are not used in the brightness
  # comparison, due to balancing effects of local gradients. The long pairs are
  # not used in the assembly of the bit vector descriptor.
  #
  # The value of dMax must be less than that of dMin.
  #
  # Default: dMax = 5.85, dMin = 8.2.
  dMax: 5.85
  dMin: 8.2

