function plot_env(subplot_index, obsPtsStore, posMinBound, posMaxBound, startPos, endPos)
    subplot(3, 1, subplot_index);
    hold on;
    
    plotEnvironment( ...
        obsPtsStore, ...
        posMinBound, ...
        posMaxBound, ...
        startPos, ...
        endPos ...
    );
end

