function x = pf_setup(dt, M, R, Q)
	x = struct( ...
	    'dt', dt, ...
        ...
	    'M', M, ...
		'R', R, ...
		'Q', Q, ...
        ...
		'X', zeros(length(R), M), ...
		'Xp', zeros(length(R), M), ...
		'w', zeros(length(R), M), ...
		'mu', 0.0, ...
		'S', 0.0 ...
	);
end
