function x = ekf_setup(dt, mu, R, Q, S)
	x = struct( ...
		'dt', dt, ...
        ...
		'mu', mu, ...
		'S', S, ...
		'R', R, ...
		'Q', Q, ...
        ...
		'mu_p', 0.0, ...
		'S_p', 0.0, ...
		'K', 0.0 ...
    );
end
