function x = kf_setup(mu, S, A, B, C, R, Q)
	x = struct( ...
		'mu', mu, ...
		'S', S, ...
        ...
		'A', A, ...
		'B', B, ...
		'C', C, ...
        ...
		'R', R, ...
		'Q', Q, ...
        ...
		'mu_p', 0.0, ...
		'S_p', 0.0, ...
		'K', 0.0 ...
	);
end
