#!/bin/bash

for file in `git status --porcelain | sed s/^...//`
do
    if [[ $file == *.cpp || $file == *.hpp ]]; then
        echo "Clang-Formatting [${file}]"
        clang-format -i ${file}
        git add ${file}
    fi
done
