function plot_hypothesis(subplot_index, map, x0, mu, sample_ind, meas_ind, meas_sample)
   	subplot(2, 2, subplot_index);
    hold on;
    
    % plot map, robot state and beliefs
    plot (map(:, 1), map (:, 2), 'bo');
    plot (map(meas_ind, 1), map(meas_ind, 2), 'ro');
    plot (x0(1), x0(2), 'gx', 'MarkerSize', 10, 'LineWidth', 2);
    
    for i = 1:length(sample_ind)
        plot (mu(1), mu(2), 'rx-', 'MarkerSize', 10, 'LineWidth', 2);
        plot( ...
            [mu(1), mu(1) + 100 * cos(meas_sample(i) + mu(3))], ...
            [mu(2), mu(2) + 100 * sin(meas_sample(i) + mu(3))], ...
            'c' ...
        );
        plot( ...
            map(meas_ind(sample_ind), 1), ...
            map(meas_ind(sample_ind),2),  ...
            'kx' ...
        );
    end
    
    % plot parameters
    title('Inlier Set and Hypothesis');
    legend( ...
        'All features', ...
        'Visible features', ...
        'Robot Position', ...
        'Robot Estimation', ...
        'Hypothesis', ...
        'Outliers' ...        
    );
    axis equal;
    axis([0 100 0 100]);
end

